// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function getDummyData() {
    return invoke<UIBoard>("get_dummy_data")
}

export type UICard = { id: number; content: string }
export type UIBoard = { columns: UIColumn[] }
export type UIColumn = { name: string; id: number; cards: UICard[] }
